<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>TestEmailAlert</fullName>
        <description>TestEmailAlert</description>
        <protected>false</protected>
        <recipients>
            <recipient>dev@pee-3.dev.welkinsuite.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/ContactFollowUpSAMPLE</template>
    </alerts>
    <alerts>
        <fullName>TestEmailAlert1</fullName>
        <description>TestEmailAlert1</description>
        <protected>false</protected>
        <recipients>
            <recipient>dev@pee-3.dev.welkinsuite.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/ContactFollowUpSAMPLE</template>
    </alerts>
    <alerts>
        <fullName>Test_description</fullName>
        <description>Test_description</description>
        <protected>false</protected>
        <recipients>
            <recipient>dev@pee-3.dev.welkinsuite.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/ContactFollowUpSAMPLE</template>
    </alerts>
    <fieldUpdates>
        <fullName>TestFieldUpdate1</fullName>
        <field>NumberField1__c</field>
        <name>TestFieldUpdate1</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>test_field_update_action</fullName>
        <field>OwnerId</field>
        <lookupValue>dev@pee-3.dev.welkinsuite.com</lookupValue>
        <lookupValueType>User</lookupValueType>
        <name>test_field_update_action</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <outboundMessages>
        <fullName>Outbound_Message</fullName>
        <apiVersion>42.0</apiVersion>
        <endpointUrl>http://test.ru</endpointUrl>
        <fields>Id</fields>
        <fields>NumberField1__c</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>dev@pee-3.dev.welkinsuite.com</integrationUser>
        <name>TestOutboundMessage1</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <outboundMessages>
        <fullName>test_outbound_message</fullName>
        <apiVersion>41.0</apiVersion>
        <description>test</description>
        <endpointUrl>https://api.metamind.io</endpointUrl>
        <fields>CreatedById</fields>
        <fields>Id</fields>
        <includeSessionId>false</includeSessionId>
        <integrationUser>dev@pee-3.dev.welkinsuite.com</integrationUser>
        <name>test_outbound_message</name>
        <protected>false</protected>
        <useDeadLetterQueue>false</useDeadLetterQueue>
    </outboundMessages>
    <rules>
        <fullName>Workflow_rule_with_formula</fullName>
        <actions>
            <name>TestEmailAlert1</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>TestFieldUpdate1</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>Outbound_Message</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <formula>$User.MobilePhone &lt;&gt; &quot;0000&quot;</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>last_rule</fullName>
        <actions>
            <name>Test_description</name>
            <type>Alert</type>
        </actions>
        <actions>
            <name>test_field_update_action</name>
            <type>FieldUpdate</type>
        </actions>
        <actions>
            <name>test_outbound_message</name>
            <type>OutboundMessage</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>User.MobilePhone</field>
            <operation>equals</operation>
            <value>1</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <timeLength>30</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>last_rule1</fullName>
        <active>false</active>
        <criteriaItems>
            <field>User.MobilePhone</field>
            <operation>equals</operation>
            <value>1</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>tws_rule1</fullName>
        <active>false</active>
        <criteriaItems>
            <field>User.Alias</field>
            <operation>notEqual</operation>
            <value>name</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>tws_rule2</fullName>
        <active>false</active>
        <criteriaItems>
            <field>User.CallCenterId</field>
            <operation>notEqual</operation>
            <value>0</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>tws_rule3</fullName>
        <active>false</active>
        <criteriaItems>
            <field>Testing_Object__c.CreatedById</field>
            <operation>startsWith</operation>
            <value>30</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
